"""MCP error codes — deterministic, no LLM interpretation."""
from __future__ import annotations

from enum import Enum


class MCPErrorCode(str, Enum):
    OK = "OK"
    DATA_MISSING = "DATA_MISSING"
    DATA_STALE = "DATA_STALE"
    DATA_HEALTH_CRITICAL = "DATA_HEALTH_CRITICAL"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    LIVE_EXECUTION_BLOCKED = "LIVE_EXECUTION_BLOCKED"
    RISK_BLOCKED = "RISK_BLOCKED"
    KILL_SWITCH_BLOCK = "KILL_SWITCH_BLOCK"
    LOG_WRITE_FAILED = "LOG_WRITE_FAILED"
    STRATEGY_NOT_APPROVED = "STRATEGY_NOT_APPROVED"
    UNKNOWN = "UNKNOWN"
